#!/usr/bin/env python
import os

# Windows
os.environ.SMING_HOME = 'C:/Users/User/Sming/Sming'
os.environ.ESP_HOME = 'C:/Espressif'

# MacOS / Linux
# os.environ.SMING_HOME = '/opt/sming/sming'
# os.environ.ESP_HOME = '/opt/esp-open-sdk'


APPNAME = 'blink'
VERSION = '0.1'

target = 'app'



def options(ctx):    
    ctx.load('sming-project', tooldir=os.path.normpath(os.path.join(os.environ.SMING_HOME, 'waf')))

def configure(ctx):
    # print(os.path.normpath(os.path.join(os.environ.SMING_HOME, 'waf')))
    ctx.load('sming-project', tooldir=os.path.normpath(os.path.join(os.environ.SMING_HOME, 'waf')))    
    pass

def build(ctx):
    ctx.load('sming-project', tooldir=os.path.normpath(os.path.join(os.environ.SMING_HOME, 'waf')))